//
//  ContactRespository.swift
//  ContactsManager
//
//  Created by alex on 11/5/2024.
//

import Foundation
import FirebaseFirestore

class ContactRespository {
    var db = Firestore.firestore()
    
    
    
    //        whereField("country", in: ["USA", "Japan"])
    //        _ = db.collection(name).whereField("userId", isEqualTo: userId)
    
    //This is a trailing closure: A function whose last parameter is a closure
    //the closure receives an contact's array and returns nothing
    func findUserContacts( fromCollection name : String, completion : @escaping ([Contact]) -> ()){

        var contacts = [Contact]()
        _ = db.collection(name)
            .order(by: "favourite", descending: true)
            .addSnapshotListener { snapshot, error in  //we add a listener, so we can listen for updates made to our db, it returns a current snapshot with the found data, and an error if there is any
                if let documents = snapshot?.documents { //we unwrap the documents inside of the snapshot
                    
                    contacts = documents.compactMap({ doc -> Contact? in    //we transform (by using compactMap) where we receive a document represented by the variable doc and return a Contact
                        let data = doc.data()
                        return Contact(id: doc.documentID, dictionary: data) // using the initializer that receives the docId and the data in a dictionary
                    })
                    
                    for contact in contacts {
                        print(contact.toString())
                    }
                    completion(contacts) //we execute the completion which is a block of code received as parameter
                   // self.contactsTableView.reloadData()
                     
                }else{
                    print("Error fetching documents \(error!)")
                    return
                }
            }
    }
    
    func addUser(withData user: User) -> Bool {
        var result = true
        let dictionary : [String: Any] = [
            "firstname": user.firstname as String,
            "lastname": user.lastname as String,
            "email": user.email as String,
            "phone": user.phone as String,
            "photo": user.photo as String,
            "registered": user.registered ?? FieldValue.serverTimestamp(), //if user.registered is nil then assignt the server timestamp
            "contacts": user.contacts
        ]
        /* The commented code works whenever we want to an autogeneratedID
        db.collection("users").addDocument(data: dictionary){ error in
            if let error = error {
                print("user could not be added \(user.email), error: \(error)")
                result = false
            }
        }*/
        //we set a particular Id so we use it
        db.collection("users").document(user.id).setData(dictionary){ error in
            if let error = error {
                print("user could not be added \(user.email), error: \(error)")
                result = false
            }
        }
        return result
    }
    
    
    func updateContact(for userId: String, withData contact: Contact) -> Bool {
        var result = true

        let dictionary : [String : Any] = [
            "firstname": contact.firstname as String,
            "lastname": contact.lastname as String,
            "email": contact.email as String,
            "phone": contact.phone as String,
            "photo": contact.photo as String,
            "favourite": contact.favourite as Bool,
            "note": contact.note as String
        ]
        
        db.collection("users/" + userId + "/contacts").document(contact.id!).updateData(dictionary){ error in
            if let error = error {
                print("Error updating document: \(error)")
                result = false
            }else{
                print("Document updated")
            }
        }

        return result
    }
    
    func addContact(for userId: String, withData contact: Contact) -> Bool {
        var result = true
        //let userAuthId = Auth.auth().currentUser?.uid
        print("User id in Show Contacts: \(userId)")
        
        let dictionary : [String: Any] = [
            "firstname": contact.firstname as String,
            "lastname": contact.lastname as String,
            "email": contact.email as String,
            "favourite": contact.favourite as Bool,
            "note": contact.note as String,
            "phone": contact.phone as String,
            "photo": contact.photo as String,
            "registered": FieldValue.serverTimestamp(),
            "tags": [String]()
        ]
        
        /*
        db.collection("users/" + userId + "/contacts").addDocument(data: dictionary){ error in
            if let error = error {
                print("Contact has not been added: \(contact.email) \(error)")
                result = false
            }else{
                print("Contact Added: \(contact.email)")
            }
            
        }
         */
        let newContactRef = db.collection("users").document(userId).collection("contacts").document()
        
        newContactRef.setData(dictionary) { error in
            if let error = error {
                print("Error adding the document \(error.localizedDescription)")
                result = false
            }else{
                print("Contact was added")
            }
        }
        
        return result
    }
    
    func deleteContact(withContactId contactId: String, for userId: String) -> Bool {
        var result = true
        
        db.collection("users/" + userId + "/contacts").document(contactId).delete(){ error in
            if let error = error {
                print("Error removing document: \(error.localizedDescription)")
                result = false
            }else{
                print("Document successfully deleted")
            }
        }
        return result
    }
    
}
